config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Read all tasks
  get "/tasks", to: "tasks#index"
  # Create one task
  get "/tasks/new", to: "tasks#new"
  post "/tasks", to: "tasks#create"
  # Display one task
  get "/tasks/:id", to: "tasks#show", as: "task"
  # Edit one task
  get "/tasks/:id/edit", to: "tasks#edit", as: "task_edit"
  patch "tasks/:id", to: "tasks#update"
  # Delete a task
  delete "/tasks/:id", to: "tasks#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  # Read all task
  def index
    @tasks = Task.all
  end
  # Read one task
  def show
    @task = Task.find(params[:id])
  end
  # New task
  def new
    @task = Task.new
  end
  # Create one task
  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to tasks_path(@task)
  end
  # Edit (get)
  def edit
    @task = Task.find(params[:id])
  end
  # Update a task (post)
  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to tasks_path
  end
  # Remove a task
  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<%=form_for(@task) do |t| %>
  <%= t.label :title %>
  <%= t.text_field :title %>

  <%= t.label :details  %>
  <%= t.text_field :details %>

  <%= t.check_box :completed %>

  <%= t.submit %>
<% end %>

<%= link_to "Back to list", tasks_path %>

app/views/tasks/index.html.erb
<h1>My tasks</h1>

<div class="my_tasks">
  <% @tasks.each do |task| %>
    <% completed = task.completed ? "fa-check-square" : "fa-square" %>
    <p>
      <i class="far <%= completed %>"></i>
      <%= link_to task[:title], task_path(task) %>

      <%= link_to task_path(task),
      method: :delete,
      data: { confirm: "Are you sure?" } do %>
        <i class="far fa-trash-alt"></i>
      <% end %>
    </p>
  <% end %>
</div>

<div class="add_task">
  <%= link_to "Add a new task", tasks_new_path %>
</div>

app/views/tasks/new.html.erb
<%=form_for(@task) do |t| %>
  <%= t.label :title %>
  <%= t.text_field :title %>

  <%= t.label :details  %>
  <%= t.text_field :details %>

  <%= t.submit %>
<% end %>

<%= link_to "Back to list", tasks_path %>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>

<div class="box">
  <p><%= @task.details  %></p>
  <% if @task.completed %>
    <i class="fa fa-check-square"> Task is completed</i>
  <% else %>
    <i class="fa fa-square"> Task is not completed</i>
  <% end %>
</div>

<div class= "edit">
  <%= link_to "Edit a task ", task_edit_path(@task) %>
</div>

<%= link_to "Back to list", tasks_path %>